apiVersion: batch/v1
kind: CronJob
metadata:
  name: kratos-k8s-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 20
      template:
        spec:
#          volumes:
#            - name: pvol
#              hostPath:
#                path: "/Users/bunyawatsingchai/GolandProjects/kratos-k8s-job/configs"
          containers:
          - name: kratos-k8s-job
            image: bunyawat/kratos-k8s-job
#            image: busybox:1.28
            imagePullPolicy: Always
#            volumeMounts:
#              - mountPath: /data/conf
#                name: pvol
          restartPolicy: Never