// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.2
// source: api/scheduler/v1/job.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecuteJobRequest) Reset() {
	*x = ExecuteJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scheduler_v1_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobRequest) ProtoMessage() {}

func (x *ExecuteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJobRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_job_proto_rawDescGZIP(), []int{0}
}

type ExecuteJobReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecuteJobReply) Reset() {
	*x = ExecuteJobReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scheduler_v1_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobReply) ProtoMessage() {}

func (x *ExecuteJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobReply.ProtoReflect.Descriptor instead.
func (*ExecuteJobReply) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_job_proto_rawDescGZIP(), []int{1}
}

var File_api_scheduler_v1_job_proto protoreflect.FileDescriptor

var file_api_scheduler_v1_job_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x7e, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x77, 0x0a, 0x0a, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x5f, 0x6a, 0x6f, 0x62, 0x42, 0x38, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x22, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2d, 0x6b, 0x38, 0x73, 0x2d, 0x6a, 0x6f, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_scheduler_v1_job_proto_rawDescOnce sync.Once
	file_api_scheduler_v1_job_proto_rawDescData = file_api_scheduler_v1_job_proto_rawDesc
)

func file_api_scheduler_v1_job_proto_rawDescGZIP() []byte {
	file_api_scheduler_v1_job_proto_rawDescOnce.Do(func() {
		file_api_scheduler_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_scheduler_v1_job_proto_rawDescData)
	})
	return file_api_scheduler_v1_job_proto_rawDescData
}

var file_api_scheduler_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_scheduler_v1_job_proto_goTypes = []interface{}{
	(*ExecuteJobRequest)(nil), // 0: api.scheduler.v1.ExecuteJobRequest
	(*ExecuteJobReply)(nil),   // 1: api.scheduler.v1.ExecuteJobReply
}
var file_api_scheduler_v1_job_proto_depIdxs = []int32{
	0, // 0: api.scheduler.v1.Job.ExecuteJob:input_type -> api.scheduler.v1.ExecuteJobRequest
	1, // 1: api.scheduler.v1.Job.ExecuteJob:output_type -> api.scheduler.v1.ExecuteJobReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_scheduler_v1_job_proto_init() }
func file_api_scheduler_v1_job_proto_init() {
	if File_api_scheduler_v1_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_scheduler_v1_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_scheduler_v1_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteJobReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_scheduler_v1_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scheduler_v1_job_proto_goTypes,
		DependencyIndexes: file_api_scheduler_v1_job_proto_depIdxs,
		MessageInfos:      file_api_scheduler_v1_job_proto_msgTypes,
	}.Build()
	File_api_scheduler_v1_job_proto = out.File
	file_api_scheduler_v1_job_proto_rawDesc = nil
	file_api_scheduler_v1_job_proto_goTypes = nil
	file_api_scheduler_v1_job_proto_depIdxs = nil
}
