// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.2
// source: api/scheduler/v1/job.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationJobExecuteJob = "/api.scheduler.v1.Job/ExecuteJob"

type JobHTTPServer interface {
	ExecuteJob(context.Context, *ExecuteJobRequest) (*ExecuteJobReply, error)
}

func RegisterJobHTTPServer(s *http.Server, srv JobHTTPServer) {
	r := s.Route("/")
	r.POST("/scheduler/execute_job", _Job_ExecuteJob0_HTTP_Handler(srv))
}

func _Job_ExecuteJob0_HTTP_Handler(srv JobHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobExecuteJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteJob(ctx, req.(*ExecuteJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteJobReply)
		return ctx.Result(200, reply)
	}
}

type JobHTTPClient interface {
	ExecuteJob(ctx context.Context, req *ExecuteJobRequest, opts ...http.CallOption) (rsp *ExecuteJobReply, err error)
}

type JobHTTPClientImpl struct {
	cc *http.Client
}

func NewJobHTTPClient(client *http.Client) JobHTTPClient {
	return &JobHTTPClientImpl{client}
}

func (c *JobHTTPClientImpl) ExecuteJob(ctx context.Context, in *ExecuteJobRequest, opts ...http.CallOption) (*ExecuteJobReply, error) {
	var out ExecuteJobReply
	pattern := "/scheduler/execute_job"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobExecuteJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
