// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-k8s-job/internal/biz"
	"kratos-k8s-job/internal/conf"
	"kratos-k8s-job/internal/data"
	"kratos-k8s-job/internal/server"
	"kratos-k8s-job/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logLogger log.Logger) (*kratos.App, func(), error) {
	mySqlAdapter, cleanup, err := data.NewMySqlAdapter(confData, logLogger)
	if err != nil {
		return nil, nil, err
	}
	rabbitMqAdapter, cleanup2, err := data.NewRabbitMqAdapter(confData, logLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jobUseCase := biz.NewJobUseCase(mySqlAdapter, rabbitMqAdapter, logLogger)
	jobService := service.NewJobService(jobUseCase)
	influxDbMiddleware, cleanup3, err := server.NewInfluxDbMiddleware(confData, logLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, jobService, logLogger, influxDbMiddleware)
	httpServer := server.NewHTTPServer(confServer, jobService, logLogger)
	app := newApp(logLogger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
