server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: test:test@tcp(127.0.0.1:3306)/test?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  amqp:
    addr: user:smd95nzXiN30SAXt@localhost:5672
  influxdb:
    addr: https://us-east-1-1.aws.cloud2.influxdata.com
    token: ---
    bucket: k8s-job