// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package mysql

import (
	"time"
)

type CurrentTemplate struct {
	TemplateName    string
	Version         string
	ID              int64
	CreateTimestamp time.Time
}
