// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package mysql

import (
	"time"
)

type ConsentTemplate struct {
	TemplateName    string
	Version         string
	ID              int64
	CreateTimestamp time.Time
}

type LastUpdatedTemplate struct {
	TemplateName      string
	Version           string
	ID                int64
	CreateTimestamp   time.Time
	ConsentTemplateID int64
}
